# Generated by Django 5.2.3 on 2025-07-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='language',
            field=models.CharField(blank=True, help_text="User's preferred language (uz/ru)", max_length=2, null=True),
        ),
    ]
