# Generated by Django 5.2.3 on 2025-06-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('entrepreneur', 'Entrepreneur'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
