# Generated by Django 5.2.3 on 2025-07-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_chat_id_users_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='language',
        ),
    ]
