# Generated by Django 5.2.3 on 2025-07-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('history', '0002_remove_searchhistory_subcategory'),
        ('place', '0004_remove_place_subcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
