# Generated by Django 5.2.3 on 2025-07-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='subcategory',
        ),
    ]
