# Generated by Django 5.2.3 on 2025-07-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_remove_searchhistory_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
