# Generated by Django 5.2.3 on 2025-07-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_searchhistory_latitude_searchhistory_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
