# Generated by Django 5.2.3 on 2025-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_alter_searchhistory_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
