# Generated by Django 5.2.3 on 2025-07-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_description_place_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
