# Generated by Django 5.2.3 on 2025-06-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_alter_place_latitude_alter_place_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name_ru',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='name_uz',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
