# Generated by Django 5.2.3 on 2025-07-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_place_description_ru_place_description_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='subcategory',
        ),
    ]
