# Generated by Django 5.2.3 on 2025-08-23 08:41

import django_minio_backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_alter_place_category_alter_place_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='near'), upload_to=django_minio_backend.models.iso_date_prefix),
        ),
    ]
